version: "3.9"

services:
  app:
    container_name: Social-Dev-Institute_api_m4
    build: .
    ports:
      - $PORT:$PORT
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
    command: bash -c "yarn typeorm migration:run -d src/migrations/data-source && yarn dev"
    volumes:
      - .:/app

  postgres:
    container_name: Social-Dev-Institute_db
    image: postgres:latest
    ports:
      - $PGPORT:$PGPORT
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
